name: Lint Commit Messages

on:
  push:
    branches:
      - master
      - "hotfix/*"
  pull_request:

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: wagoid/commitlint-github-action@v6
        with:
          # Commit messages here are written by GitHub Copilot and don't
          # follow Conventional Commits, so lint without failing the build.
          failOnErrors: false
          firstParent: true
